### ISSUE TITLE
Terraform Provider produced inconsistent result with provision token

### ISSUE THREAD

**Issue by AgDude** [gravitational/teleport-plugins#543]
I am creating a new token with terraform and while the token is created, the terraform apply fails with the following message:

```
module.dev_teleport_node.teleport_provision_token.tenant: Creating...
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to module.dev_teleport_node.teleport_provision_token.tenant, provider "module.dev_teleport_node.provider[\"gravitational.com/teleport/teleport\"]" produced an unexpected new value: .metadata:
│ inconsistent values for sensitive attribute.
│ 
```

This is terraform 1.1.7 and teleport provider version 1.9.3 (same result with build from master). Run on darwin_arm64 (built provider locally)

**Comment by AgDude** [comment]
I was able to reproduce this with a very simple terraform module, and it seems to go away when the "namespace" property is removed.

example (slightly different error message):
```
resource "teleport_provision_token" "tenant" {
    metadata = {
        name = "very-secret-token"
        description = "Test for github issue https://github.com/gravitational/teleport-plugins/issues/543"
        namespace = "github_test"
        expires = "2022-05-10T00:00:00Z"
        labels = {
            node_type = "github_test"
        }
    }

    spec = {
        roles = ["Node", "App"]
    }
}
```

**Comment by marcoandredinis** [comment]
Hey @AgDude 

Thank you for the report

Can you please let me know if you have cache enabled in the teleport cluster?
The config should have something like this:
```yaml
teleport:
  cache:
    enabled: true # or false
```

**Comment by AgDude** [comment]
I have no cache section in my teleport config, so it is the default value (I am not sure what the default is).

**Comment by marcoandredinis** [comment]
It should be on by default
After some local tests, my best guess so far is that it is related with cache

May I please ask you to run a test for me?
Rebuild the provider using the code from this PR https://github.com/gravitational/teleport-plugins/pull/556 and let me know how it goes

**Comment by marcoandredinis** [comment]
Cache issues should be fixed since 9.3.4
Can you please try again?

**Comment by AgDude** [comment]
Thanks for making the update. It still isn't quite right.  Here is the output using plugin version 9.3.7.

```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to teleport_provision_token.test, provider "provider[\"gravitational.com/teleport/teleport\"]" produced an unexpected new value: .metadata.namespace: was cty.StringVal("github_test"), but now
│ cty.StringVal("default").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

**Comment by marcoandredinis** [comment]
Yeah... so... namespaces are not actually a well tested or even supported feature.
You should set it to `default` or omit it.

However, that leads me to another question: what did you expect the `namespace` property to do?
Or were you just setting it to kind of categorize things when looking back at the token?
